qdrant_endpoint: "https://3ae768f8-49b7-499a-89ae-b65a1e8afd00.us-east4-0.gcp.cloud.qdrant.io"
api_key: "eelf_lfy8Xm9qM6ai912EIlsYn940hFYQ51XBQteC6OaDo071nwuNw"
openAIAPIkey: "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"
website_url: "https://clorox.com/learn"
#Added by Satish